[package]
name = "weather_cli_project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features=["dervive"]}
reqwest = {version="0.12.5", features=[
   "blocking", "json"
]}
serde_json = "1.0"
colored = "2.0"